name: Backend-CICD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'content/lambda/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: content/

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_IAM_ROLE }}
        aws-region: us-east-1

    - name: Zip lambda function
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r dir.zip lambda

    - name: Copy files to the s3 website content bucket
      run:
        ls *
