name: Backend-CICD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'content/lambda/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: content/lambda/

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_IAM_ROLE }}
        aws-region: us-east-1

    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Build Image
      run: |
        docker build -t ${{ secrets.ECR_URL }}/lambda:${{ steps.vars.outputs.sha_short }} .
        docker push ${{ secrets.ECR_URL }}/lambda:${{ steps.vars.outputs.sha_short }}

    - name: Update Lambda
      run:
        aws lambda update-function-code --function-name ${{ secrets.AWS_LAMBDA_NAME }} --image-uri ${{ secrets.ECR_URL }}/lambda:${{ steps.vars.outputs.sha_short }}
