name: Frontend-CICD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'content/frontend/**'
  workflow_dispatch:
  
defaults:
  run:
    working-directory: content/frontend

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_IAM_ROLE }}
        aws-region: us-east-1

    - name: Copy files to the s3 website content bucket
      run:
        aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET_NAME }}/
        
    # Ideally this would be manual since invalidating the cache isn't required for every update
    - name: Invalidate the Cloudfront Cache
      run:
        aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} --paths '/*'
